cargo run --release < test_case/t10.in
cargo run --release < test_case/t20.in
cargo run --release < test_case/t30.in
cargo run --release < test_case/t40.in
cargo run --release < test_case/t50.in
cargo run --release < test_case/t60.in
cargo run --release < test_case/t70.in
cargo run --release < test_case/t80.in
cargo run --release < test_case/t90.in
cargo run --release < test_case/t100.in
cargo run --release < test_case/t110.in
cargo run --release < test_case/t120.in
cargo run --release < test_case/t130.in
cargo run --release < test_case/t140.in
cargo run --release < test_case/t150.in
cargo run --release < test_case/t160.in
cargo run --release < test_case/t170.in
cargo run --release < test_case/t180.in
cargo run --release < test_case/t190.in
cargo run --release < test_case/t200.in
cargo run --release < test_case/t210.in
cargo run --release < test_case/t220.in
cargo run --release < test_case/t230.in
cargo run --release < test_case/t240.in
cargo run --release < test_case/t250.in
cargo run --release < test_case/t260.in
cargo run --release < test_case/t270.in
cargo run --release < test_case/t280.in
cargo run --release < test_case/t290.in
cargo run --release < test_case/t300.in
